import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { OrderProvider } from "../context/OrderContext";
import Footer from "./components/footer/footer";
import TopNav from "./components/navbar/TopNav";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Lil Bits",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <OrderProvider>
      <html lang="en">
        <body className={inter.className}>
          <TopNav />
          {children}
          <Footer />
        </body>
      </html>
    </OrderProvider>
  );
}
